# Generated by Django 3.1.7 on 2021-03-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('experience', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=30)),
                ('add_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FirstYearStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'FeMale'), ('others', 'Others')], default=None, max_length=6)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('xii_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admission_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('std', models.IntegerField(default=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(max_length=50)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=1000)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist', models.ManyToManyField(to='myapp.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'FeMale'), ('others', 'Others')], default=None, max_length=6)),
                ('package', models.IntegerField(blank=True, help_text='in LPA')),
                ('address', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, default='no_photo.jpg', help_text='Supported format: jpeg/gif/png; max-size:50kb', upload_to='photos')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
        ),
    ]
